version: 1.2
workflows:
  - name: sv_evaluation
    subclass: WDL
    description: Evaluate structural variant (SV) calls against a truth set using truvari and sveval
    primaryDescriptorPath: /workflow.wdl
    testParameterFiles:
      - /test/test.inputs.json
    authors:
      - name: Jean Monlong
        email: jean.monlong@gmail.com
